Adding LICENSE file to project
jenkinsci/workflow-job-plugin pull request #138
Opened 2019-08-27 05:12 UTC by kshithijiyer

2019-08-27 13:48 UTC, kshithijiyer commented
It is good to have a dedicated License file. Not every project will have a pom.xml and when someone is looking for a place to find what license a project is open sourced under than he'll generally look for a license file.

2019-08-27 13:52 UTC, kshithijiyer commented
The intent here is to have a general license file common to all the code and each author can have their own license added below that one in the same file. So if someone what's the know the licenses of the code he/she can see the license file which will state Licenses for all the code in a repo.

2022-01-24 19:34 UTC, jglick requested changes

2022-01-24 19:34 UTC, jglick commented on LICENSE
> +Copyright (c) 2017 CloudBees, Inc.
```suggestion
Copyright (c) 2022 CloudBees, Inc. and other contributors.
```

2022-09-20 12:34 UTC, closed without merging