Feat: Un-inline WorkflowJob/configure-entries.jelly
jenkinsci/workflow-job-plugin pull request #411
Opened 2024-02-03 08:20 UTC by krisstern

### Description
**Testing done**. Tried the functionality which appears intact after the code modifications, except for the original testing steps outlined in https://issues.jenkins.io/browse/JENKINS-69916. The checkURL validation is now completely gone. This work follows the upstream changes in https://github.com/jenkinsci/jenkins/pull/8866, especially the ones in `core/src/main/java/hudson/model/AbstractProject.java`. The only requirement for this patch to work is that we will need the minimum Jenkins version requirement to set at `2.443`. 

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-02-03 10:37 UTC, mawinter69 commented
You can't depend on https://github.com/jenkinsci/jenkins/pull/8866 because this change AbstractProject and WorkflowJob is not inheriting from it. So no need to change the jenkins version. You would need to also implement the doCheckDisplayNameOrNull method.

Given that we have this now in MatrixProject (open PR https://github.com/jenkinsci/matrix-project-plugin/pull/130), core (the mentioned change), folder plugin (https://github.com/jenkinsci/cloudbees-folder-plugin/blob/233481b4bb4accfe8582ad2f5c922168022af31d/src/main/java/com/cloudbees/hudson/plugins/folder/AbstractFolderDescriptor.java#L138) and here maybe we can have an AbstractItemDescriptor interface with a default implementation for that doCheckDisplayNameOrNull and have all 4 places implement that interface

2024-02-04 08:16 UTC, krisstern commented
Hi @mawinter69 I have tried my best to apply the suggesions from your review. But I might have missed some important details though. If that if the case please let me know. Thanks!

2024-02-04 09:23 UTC, mawinter69 commented
> Hi @mawinter69 I have tried my best to apply the suggesions from your review. But I might have missed some important details though. If that if the case please let me know. Thanks!

Sorry seems my wording was not precise enough. The thing with the `AbstractItemDescriptor` is something that would need to be implemented in Jenkins core, not in a plugin. This would allow the 4 places that now all have duplicated code for the `doCheckDisplayNameOrNull ` method now to just add the dependency on that interface.

So for now you will need to add this method to the  Descriptor of WorkflowJob, not WorkflowJob directly

2024-04-09 14:43 UTC, krisstern commented
Let me follow up on this shortly

2024-04-13 08:58 UTC, krisstern commented
Working on the upstream PR pending review(s): https://github.com/jenkinsci/jenkins/pull/9150

2024-04-21 08:02 UTC, daniel-beck requested changes
With the core change, should be good enough just deleting the `checkUrl`?

Should increase the core dependency to the snapshot (and then the release once out).

2024-04-21 08:02 UTC, daniel-beck commented on src/main/java/org/jenkinsci/plugins/workflow/job/AbstractItemDescriptor.java
> +package org.jenkinsci.plugins.workflow.job;
Delete this file.

2024-04-21 08:02 UTC, daniel-beck commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> +import hudson.util.FormValidation;
Revert, unused.

2024-04-21 08:02 UTC, daniel-beck commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> +import org.kohsuke.stapler.QueryParameter;
Revert, unused.

2024-04-21 08:02 UTC, daniel-beck commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> +public final class WorkflowJob extends Job<WorkflowJob,WorkflowRun> implements LazyBuildMixIn.LazyLoadingJob<WorkflowJob,WorkflowRun>, ParameterizedJobMixIn.ParameterizedJob<WorkflowJob, WorkflowRun>
Revert.

2024-04-21 08:02 UTC, daniel-beck commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> -
Revert.

2024-05-02 14:08 UTC, krisstern commented on src/main/java/org/jenkinsci/plugins/workflow/job/AbstractItemDescriptor.java
> +package org.jenkinsci.plugins.workflow.job;
Done

2024-05-02 14:08 UTC, krisstern commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> +import hudson.util.FormValidation;
Done

2024-05-02 14:08 UTC, krisstern commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> +import org.kohsuke.stapler.QueryParameter;
Done

2024-05-02 14:09 UTC, krisstern commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> +public final class WorkflowJob extends Job<WorkflowJob,WorkflowRun> implements LazyBuildMixIn.LazyLoadingJob<WorkflowJob,WorkflowRun>, ParameterizedJobMixIn.ParameterizedJob<WorkflowJob, WorkflowRun>
Done

2024-05-02 14:09 UTC, krisstern commented on src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
> -
Done

2024-05-02 14:09 UTC, krisstern commented
Hi @daniel-beck I have just made the changes as suggested

2024-08-23 16:42 UTC, daniel-beck approved these changes
Is this significant enough to need a core dependency with https://github.com/jenkinsci/jenkins/pull/9150, or can we tolerate this not working with older cores?

2024-10-01 23:35 UTC, basil approved these changes
PCT: https://github.com/jenkinsci/bom/pull/3657
ATH: https://github.com/jenkinsci/acceptance-test-harness/pull/1751

2024-10-02 14:46 UTC, basil commented
Retested manually against 2.477.x

2024-10-02 14:46 UTC, merged

2024-10-02 15:12 UTC, jglick commented on pom.xml
> +                <artifactId>bom-2.462.x</artifactId>
Is a `bom-2.477.x` in preparation?

2024-10-02 15:13 UTC, jglick commented on pom.xml
> +            <!-- TODO JENKINS-73339 until in parent POM, work around https://github.com/jenkinsci/plugin-pom/issues/936 -->
pending https://github.com/jenkinsci/plugin-pom/pull/1004#issuecomment-2379382600 IIUC